# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0005_auto_20171023_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveler',
            name='photo',
            field=models.ImageField(upload_to='trav_avats/'),
        ),
    ]
