# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 14:35
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0007_auto_20171120_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(default=datetime.date(2017, 11, 24), verbose_name='Дата бронирования'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_date',
            field=models.DateField(verbose_name='Дата отъезда'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hw.Hotel', verbose_name='Отель'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='price',
            field=models.IntegerField(verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_date',
            field=models.DateField(verbose_name='Дата заезда'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hw.Traveler', verbose_name='Постоялец'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='adress',
            field=models.CharField(max_length=30, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='features',
            field=models.ManyToManyField(blank=True, to='hw.HotelFeature', verbose_name='Особенности'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='photo',
            field=models.ImageField(blank=True, default='hotel_avats/default.png', upload_to='hotel_avats/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='hotelfeature',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='photo',
            field=models.ImageField(blank=True, default='trav_avats/default.png', upload_to='trav_avats/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
